export const BLOGS_LOAD_REQUEST = 'BLOGS_LOAD_REQUEST';
export const BLOGS_LOAD_SUCCESS = 'BLOGS_LOAD_SUCCESS';
export const BLOGS_LOAD_FAIL = 'BLOGS_LOAD_FAIL';

export const BLOGS_SINGLE_LOAD_SUCCESS = 'BLOGS_SINGLE_LOAD_SUCCESS';
export const BLOGS_SINGLE_LOAD_FAIL = 'BLOGS_SINGLE_LOAD_FAIL';
